services:
  db:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campus_voice_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
